### ISSUE TITLE
Trinity folder names

### ISSUE THREAD

**Issue by ghost** [MikeWLloyd/Sequencing-Coverage-Scripts#1]
Hi Mike, 

I've notice the the Trinity version that works in Phyluce now adds an "_trinity" to the folder names, making the input names different than what your scripts accepts (e.g., ./Trinity_Assemblies/[TAXON1]**_trinity**/contigs.fasta).  I've been trying to deal with this by just renaming the trinity files, but that makes me weary since I could corrupt them by doing so. Do you have a more elegant way to solve this issue?

**Comment by MikeWLloyd** [comment]
I don't have a more elegant way of catching old and new trinity output, that would take a bit to work up. As a quick fix, you could modify the script rather than the file names. I don't have any files to test this change with, but try changing: 

Line78: 
`file_start=args.input+'/'+line+'/'`
changed to: 
`file_start=args.input+'/'+line+'_trinity/'`

see if that gets around the issue. It may break something else downstream, let me know what happens.

**Comment by ghost** [comment]
Thanks! I'll let you know if any issues show up

**Comment by MikeWLloyd** [comment]
Assuming all is OK here and I am closing, reopen if needed.
